// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bceiprktlaanhsojixvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZWlwcmt0bGFhbmhzb2ppeHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MTIxMzMsImV4cCI6MjA1NjI4ODEzM30.vKBgmfNqKeiuOz9NDDtycANEHJN7D2nDtRhR31GhIbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);